### ISSUE TITLE
图片跨域问题导致无法复制和下载

### ISSUE THREAD

**Issue by kai2128** [YunYouJun/girid#4]
![image](https://user-images.githubusercontent.com/78791519/230413514-af51ab00-4071-4abe-80c4-49945ba9e924.png)

**Comment by YunYouJun** [comment]
使用 Vercel 代理修复。

![Girid-动画角色印象表](https://user-images.githubusercontent.com/25154432/232329535-c353e0bd-6515-41f1-9731-386286880075.png)
