### ISSUE TITLE
样式有点问题

### ISSUE THREAD

**Issue by sgj123456** [YunYouJun/girid#5]
![Screenshot_20240104-191122_Chrome.png](https://github.com/YunYouJun/girid/assets/94758390/4546c9bc-6d09-4ba1-bc83-52c3f61c3ffd)

![Screenshot_20240104-191130_Chrome.png](https://github.com/YunYouJun/girid/assets/94758390/b65f6043-8a6f-4b8b-9434-f388455ed964)

![Screenshot_20240104-191140_Chrome.png](https://github.com/YunYouJun/girid/assets/94758390/8472a97f-d29c-4f5c-8b42-20489ea7a985)

- 在`朋友`和`设置`的URL下刷新会出现`404`
- `朋友`页面的`rows`和`cols`栏在移动端排版很鬼畜
- `朋友`和`主页`显示类似的东西，但是只有`朋友`的gird撑满屏幕

**Comment by YunYouJun** [comment]
Fixed.
